### PR TITLE
KazooClient hosts list should accept a list of multiple endpoints.

### LINKED ISSUE #411: KazooClient hosts list should accept a list of multiple endpoints
Currently `KazooClient` accepts a list of multiple hosts as a single concatenated string: http://kazoo.readthedocs.io/en/latest/api/client.html#kazoo.client.KazooClient

It seems the API would be more pythonic if it also accepted the hosts as a native list:

```
['zk01:2181', 'zk02:2181', 'zk03:2181']
```

I can submit a PR for this, but only if I get confirmation the core team is open to this feature request.

See also https://github.com/DataDog/dd-agent/issues/2943#issuecomment-255780694 - for example, `KafkaClient` supports both the concatenated string and native list formats.

### PR DESCRIPTION
**Pull request by eribeiro**
Closes #411

### CODE REVIEW

**Comment by jeffwidman** [comment]
Looks fantastic, nice job. 

I'm not super excited about a list supporting both strings and tuples as formats, but OTOH while the strings are extremely common format for most libraries the tuples are very explicit, so it is handy to have both. So I support your decision to support both formats.

Could you add two more test cases where the hostname is an IP address and not a domain name? 
I'd make one a IPv4 and one an IPv6 address just because people often split name/port on a `:` but IPv6 complicates that... and the test case protects in case anyone refactors this code down the road.

**Comment by eribeiro** [comment]
@jeffwidman Thanks for the comment, very insightful. Gonna add more test cases. :+1:

**Comment by jeffwidman** [comment]
Some test failures. The python 2.6 failure is probably acceptable breakage as it doesn't support ipv6, that's up to the maintainers, but the inconsistent use of tabs/spaces should get fixed before merging.

**Comment by eribeiro** [comment]
@jeffwidman Thanks, gonna fix the inconsistency asap. Even on python 2.7, I've found that `urllib_parse.urlsplit` still have many problems parsing the IPv6 addresses. :thinking:

**Comment by eribeiro** [comment]
@jeffwidman Hi, I tried to fix the inconsistencies between tabs/spaces. Hope everything is fine now, but let me know if something skipped, please 😃

@harlowja Does this PR makes sense? Any other file to change? Please, let me know. 

Best regards!

**Comment by jeffwidman** [comment]
LGTM. Spot-checked a few test failures and they are python 2.6 choking on IPv6. Personally, I think this lib should solve that by dropping support for python 2, but I'm not one of the maintainers, so that's up them.

**Comment by jeffwidman** [comment]
@harlowja Any comment on this?

**Comment by bbangert** [comment]
We can't drop support for Python 2, though I would like to drop support for Python 2.6 as that should be long dead.

**Comment by bbangert** [comment]
@jeffwidman you seem most active on github and this PR, would you be up for fixing this to work on Python 2.6? If so I can include it in the next release.

As is, I'm closing this for now, but please re-open it if changes are made that allow this to be merged.

**Comment by jeffwidman** [comment]
@bbangert Thanks for looking at this. 

Like the other PR's that you just closed that I commented on, I do think it's a bit premature to close this one as well. 

There was zero feedback on this from any of the maintainers until last night, so I don't blame @eribeiro for not spending any time on this until he knew whether it actually had a chance of getting merged.

I've literally never seen another project where a PR in process is marked as closed like this when the maintainers are interested in it, but just requesting further updates. Typically my experience is that marking something as `Closed` means the maintainers are rejecting it as a bad idea or such a poorly coded implementation that it's not worth working with the submitter to update it. 

Personally, I'd prefer to help @eribeiro finish this by giving feedback etc rather than me finishing it as it's better in the long run to encourage someone new to open source, plus he deserves the credit as he already did the brunt of the work.

**Comment by jeffwidman** [comment]
Also, @bbangert you requested 2.6 support above, but I see in https://github.com/python-zk/kazoo/commit/2faba9ff3bdeff151ac6c922bf65b2dcf9c7bd7b you dropped official support for 2.6, so does this PR actually still need to be updated for 2.6?

**Comment by bbangert** [comment]
Sorry about that, due to the backlog of PR's kazoo ended up in a bad situation where there's just so many PR's I have no way to track which ones people are interested in updating, and which ones people aren't. The longer the PR list, the less anyone wanted to maintain Kazoo at all, so clearing them out so that it was clear what was actionable and what wasn't feels like the only sane UX hack around a bad usability issue. (If only Github would let me 'snooze' a PR so that it can easily be filtered out).

If you have any suggestions for alternative ways to filter out PR's that are desired but out-of-date, I'd love to use that as it wasn't my intention at all to insult/annoy anyone. This was the most immediate and obvious way to filter the list of actionable PR's that I could see, so I went that route. Sorry again about not being able to look into this earlier.

**Comment by bbangert** [comment]
Regarding 2.6 support, I'm fine ignoring that now that we'll be dropping Python 2.6 support. I think the PR only needs a rebase and it'll be good to go. I'll re-open it and see if GH can automatically rebase it.

**Comment by jeffwidman** [comment]
> Sorry about that, due to the backlog of PR's kazoo ended up in a bad situation where there's just so many PR's I have no way to track which ones people are interested in updating, and which ones people aren't. The longer the PR list, the less anyone wanted to maintain Kazoo at all, so clearing them out so that it was clear what was actionable and what wasn't feels like the only sane UX hack around a bad usability issue. (If only Github would let me 'snooze' a PR so that it can easily be filtered out).

I completely understand. I help maintain a number of projects that have just this kind of issue, and I myself go through and close old PR's that have been sitting idle longer than 6-12 months, it's just that I try to give folks a gentle nudge first, especially if it looks like they're first-time contributors to open source.

**Comment by bbangert** [comment]
Oh, the only other update this needs is the commit needs to be altered to the style in the CONTRIBUTING doc. Otherwise the change won't be included in the CHANGES.md file. If the original author needs any help updating the commit and force pushing I'd be happy to help, a rebase and commit update should also remove the need for my merge commit.

**Comment by bbangert** [comment]
@eribeiro Did you want to update this?

**Comment by jeffwidman** [comment]
I haven't forgotten about this either, and if @eribeiro doesn't drop in, I am happy to update this as well.

**Comment by eribeiro** [comment]
@jeffwidman @bbangert Hey, thanks for taking your time to discuss and instruct me on improving this PR. It is **really** appreciated! 😃 

Well, I have changed the commit message to the one indicated by bbangert as well as rebased the branch to the master. Please, let me know if there's any other pending work on this PR. I am glad to make any required changes.

**Comment by bbangert** [comment]
@eribeiro thanks! nice work!

**Comment by eribeiro** [comment]
@jeffwidman @bbangert Thanks **a lot** for your support and patience. It meant a lot to me. 👍

**Pull request merged**
