### PR TITLE
Add an eventlet based handler

### PR DESCRIPTION
**Pull request by harlowja**
Integrate eventlet *handler* support into kazoo so that along with [gevent,
threading] handlers there can now be a dedicated eventlet handler for
projects that need to (or want to) use eventlet (such as those working
in the openstack community). The ``requirements_eventlet.txt`` file lists
the optional eventlet requirement(s) that needs to be satisfied when this
new handler is used.

### CODE REVIEW

**Comment by bbangert** [comment]
Doesn't this need to modify travis.yml to install eventlet so that travis runs its tests?

**Comment by harlowja** [comment]
Thought I got that, might have not; checking.

**Comment by bbangert** [comment]
I think you did, travis says it ran eventlet tests.

**Comment by bbangert** [comment]
r+

**Pull request merged**
