### PR TITLE
feat(core): add support for GSSAPI authentication (Kerberos)

### PR DESCRIPTION
**Pull request by StephenSorriaux**
This adds the possibility to connect to Zookeeper using the GSSAPI mechanism a.k.a Kerberos.

__How to connect to ZK using GSSAPI?__
The following libs must be installed:
- [pure-sasl](https://github.com/thobbs/pure-sasl)
- [kerberos](https://github.com/apple/ccs-pykerberos)

This is an example that shows how connect to Zookeeper using Kerberos auth where test@EXAMPLE.COM is a Kerberos principal and kerberos.example.com the DNS to access to the kdc:
```
from kazoo.client import KazooClient
from kazoo.security import make_acl

kerberos_principal = 'test@EXAMPLE.COM'
zk = KazooClient(hosts='172.17.0.2:2181', auth_data=[('gssapi', kerberos_principal)], kerberos_server_principal='kerberos.example.com')
zk.start()
acl = make_acl('sasl', credential=kerberos_principal, all=True)
zk.ensure_path('/test', acl=(acl,))
zk.get('/test')
zk.stop()
```
`kerberos_principal` can be `None` if usage of Kerberos credential cache is wanted.

__How did you test this?__
Using a Docker container where Kerberos is configured and where Zookeeper is using it for authentication. Docker images are available in my repo https://github.com/StephenSorriaux/docker-kerberos-zookeeper
I didn't add any unit test for this new feature since it requires a running Kerberos server...

I updated the `add_auth` method documentation but it seems to me that this might not be the best place to put it since this method can not be used with `sasl` or `gssapi` schemes. I may move it elsewhere in another PR.

### CODE REVIEW

**Comment by anthonyliao** [comment]
Hi @StephenSorriaux, this PR looks good. I was able to validate it against my Kerberos server. When can we expect to get this merged and release?

**Comment by StephenSorriaux** [comment]
@anthonyliao Hi, thanks for your test.

I am currently not sure if the behaviour is good when the ticket expires... did you get the chance to test this on your side? I hope to merge it very soon if the behaviour is good.

**Comment by anthonyliao** [comment]
Just tested this. My observations:
1. Ticket needs to be valid before connecting otherwise the Kazoo client fails (i.e. must exist in cache and not expired)
2. If the ticket is valid and the session is authenticated by ZooKeeper, ZooKeeper will continue to honor the ticket even if it expires during the session (i.e. doesn't check ticket again until session is terminated and re-established)

Here's my test:

1. Created a valid ticket for 5 minutes
```
$ kinit -l 5m anthonyliao
Password for anthonyliao:

$ klist
Ticket cache: FILE:/tmp/krb5cc_1524355
Default principal: anthonyliao

Valid starting       Expires              Service principal
12/7/2018 22:01:34  12/7/2018 22:06:32  tgt/testrealm.com@testrealm.com
```

2. Ran test.py
```
from kazoo.client import KazooClient
from kazoo.security import make_acl
import time

zk = KazooClient(hosts='zookeeperhost.fakeaddress.com', auth_data=[('gssapi', 'anthonyliao')], kerberos_server_principal='zookeeperhost.fakeaddress.com')
zk.start()

acl1 = make_acl('sasl', credential='anthonyliao', write=True)
acl2 = make_acl('world', credential='anyone', read=True, create=True, delete=True, admin=True)
zk.ensure_path('/TEST_NAMESPACE/testnode', acl=(acl1,acl2))

i = 0
while True:
	zk.set('/TEST_NAMESPACE/testnode', 'data' + str(i))
	print('incrementing data counter:' + str(i))
	i = i + 1
	time.sleep(1)
```
3. Use ZooKeeper's default libraries (`zkCLI.cmd`) to connect as an **unathenticated** user and fetched the data at the znode
`get /TEST_NAMESPACE/testnode`
4. After 15 minutes, confirmed that znode was still updating
5. Checked if the ticket was auto-renewed - **it was not!**
```
klist

Ticket cache: FILE:/tmp/krb5cc_1524355
Default principal: anthonyliao

Valid starting       Expires              Service principal
12/7/2018 22:01:34  12/7/2018 22:06:32  tgt/testrealm.com@testrealm.com
12/7/2018 22:01:42  12/7/2018 22:06:32  zookeeper/zookeeperhost.fakeaddress.com@testrealm.com
```
6. Killed and re-ran `test.py`. Script threw an `Ticket expired` exception
 ```
$ python2 test.py
No handlers could be found for logger "kazoo.client"
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/cygdrive/c/Users/anthonyliao/kazoo-feat-add-gssapi-support/kazoo/protocol/connection.py", line 521, in zk_loop
    if retry(self._connect_loop, retry) is STOP_CONNECTING:
  File "/cygdrive/c/Users/anthonyliao/kazoo-feat-add-gssapi-support/kazoo/retry.py", line 120, in __call__
    return func(*args, **kwargs)
  File "/cygdrive/c/Users/anthonyliao/kazoo-feat-add-gssapi-support/kazoo/protocol/connection.py", line 560, in _connect_loop
    status = self._connect_attempt(host, port, retry)
  File "/cygdrive/c/Users/anthonyliao/kazoo-feat-add-gssapi-support/kazoo/protocol/connection.py", line 588, in _connect_attempt
    read_timeout, connect_timeout = self._connect(host, port)
  File "/cygdrive/c/Users/anthonyliao/kazoo-feat-add-gssapi-support/kazoo/protocol/connection.py", line 730, in _connect
    challenge = self.sasl_cli.process()
  File "/usr/lib/python2.7/site-packages/puresasl/client.py", line 16, in wrapped
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/puresasl/client.py", line 148, in process
    return self._chosen_mech.process(challenge)
  File "/usr/lib/python2.7/site-packages/puresasl/mechanisms.py", line 495, in process
    kerberos.authGSSClientStep(self.context, '')
GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Ticket expired', -1765328352))

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    zk.start()
  File "/cygdrive/c/Users/anthonyliao/kazoo-feat-add-gssapi-support/kazoo/client.py", line 587, in start
    raise self.handler.timeout_exception("Connection time-out")
kazoo.handlers.threading.KazooTimeoutError: Connection time-out
```

**Comment by StephenSorriaux** [comment]
@anthonyliao Many thanks for your tests. So I am currently missing the ticket's renewing feature if I want to merge this since the Zookeeper's Java client seems to have this feature (https://github.com/apache/zookeeper/blob/cb9f303bda9137d1aebe8eff3eab85c8a59f3cdd/zookeeper-server/src/main/java/org/apache/zookeeper/Login.java#L22)

**Comment by anthonyliao** [comment]
@StephenSorriaux Yep. Is there anything you need from me?

**Comment by StephenSorriaux** [comment]
@anthonyliao Thank you! If you have some times, you can open a PR on my fork to my current branch in order to add the ticket renewing feature. I will also try to look at it this week.

**Comment by StephenSorriaux** [comment]
Closing this PR since #546 was merged.

**Pull request closed without merging**
