### PR TITLE
System call interrupts

### PR DESCRIPTION
**Pull request by jacksontj**
This is a followup to #250

This PR includes 2 patches both fixing more interrupt issues. Basically this is an upstream issue (in python-- http://bugs.python.org/issue20611).

The first patch changes my previous fix (#250) from raising a timeout to retrying-- the issue we see is that the rest of the kazoo code assumes that a timeout is a timeout (which is reasonable). So instead of reworking all timeouts within kazoo, we can simply retry.

The second patch handles the same during connection setup.

### CODE REVIEW

**Comment by jacksontj** [comment]
Seems that all the tests failed with some gzip error? Sounds unrelated-- esp. since all tests failed with the same error (and I don't get that error locally)

**Comment by jacksontj** [comment]
cc @bbangert @harlowja 
Since you guys helped review my patch last time-- I figure you'll be interested in this one as well.

**Comment by bbangert** [comment]
This looks fine to me, but I'm also stumped by the Travis errors.

**Comment by jacksontj** [comment]
@bbangert do you know of a way to re-trigger the run? From the errors it looks like travis might have had an issue.

**Comment by bbangert** [comment]
@jacksontj yup, triggered it again just now

**Comment by jacksontj** [comment]
This is really odd, when I run the tests locally they seem to pass just fine. Is there some way to get additional debugging info from travis? Or is there someone who maintains it that we could ping?

**Comment by jacksontj** [comment]
@bbangert any ideas who we can talk to?

**Comment by bbangert** [comment]
@jacksontj not offhand. there might have been a few failures before this one though on master, so I need to retry them as well to see when it broke for good

**Comment by bbangert** [comment]
@jacksontj ok, well, I went back to a prior travis test that only had 2 fail, and reran it.... and then they all failed. I'm guessing something on Travis has changed, such that all our tests are now insta-fail.

**Comment by bbangert** [comment]
I've found the issue. The mirror chosen no longer has 3.4.7, I reverted that so that the tests can run. Will be restarting this shortly.

**Comment by bbangert** [comment]
@jacksontj and of course, that fix won't help you until you rebase against master. Can you rebase against master?

**Comment by bbangert** [comment]
@jacksontj looks like there's 1 error reported.

```
======================================================================

ERROR: test_dirty_sock (kazoo.tests.test_connection.TestConnectionHandler)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/python-zk/kazoo/kazoo/tests/test_connection.py", line 229, in test_dirty_sock

    wait(lambda: client.handler.select([read_sock], [], [], 0)[0] == [])

  File "/home/travis/build/python-zk/kazoo/kazoo/tests/util.py", line 105, in __call__

    if func():

  File "/home/travis/build/python-zk/kazoo/kazoo/tests/test_connection.py", line 229, in <lambda>

    wait(lambda: client.handler.select([read_sock], [], [], 0)[0] == [])

TypeError: 'NoneType' object is unsubscriptable
```

**Comment by jacksontj** [comment]
@bbangert fixed the issues :) now travis is happy.

**Comment by bbangert** [comment]
@jacksontj looks good!

**Pull request merged**
