### PR TITLE
fix attribute error when deleting node if self.node was not yet assigned

### PR DESCRIPTION
**Pull request by trbs**
The lock recipe can fail with attribute error when connection error happens before `self.node = node` is called.

Fixed by explicitly defining `self.node = None` in `__init___` and checking it before deleting the node when lock could not be acquired.

### CODE REVIEW

**Comment by bbangert** [comment]
I'm actually not sure a test can reliably cause this, but it definitely deserves a changelog entry.

**Comment by trbs** [comment]
We hit the problem because we have a lock that does not retry when an error happens trying to acquire the lock. When we restarted one of our ZK nodes we got this ```AttributeError``` on the ```Lock``` object. I assume this is also why nobody else hit and reported the issue. As normally one will try and get another ZK node to try and acquire the lock.

If kazoo has some test infrastructure to simulate a ZK failure after N operations then we might be able to test this reliably by KazooRetry(max_tries=0) and have the mock ZK node fail after the first ZK operation (ensurePath?) in ```_inner_acquire```.

Reading the recipe code I was expecting this to be a programming error that slipped into the code. I cannot find a reason why ```self.node``` is not explicitly declared in ```__init__``` while the other major attributes of the ```Lock``` are.

**Comment by trbs** [comment]
changelog entry added

**Comment by bbangert** [comment]
Please re-open to rebase and update as needed.

**Pull request closed without merging**
