### PR TITLE
chore: 2.6.1 release and changelog

### PR DESCRIPTION
**Pull request by StephenSorriaux**
Releasing 2.6.1 version with latest fixes.

### CODE REVIEW

**Comment by jeffwidman** [comment]
LGTM, thanks for driving this!

**Comment by StephenSorriaux** [comment]
I just added a commit to deploy only on a specific job. Previously 3 jobs were trying to deploy on tags.

**Comment by bbangert** [comment]
Thanks!

**Comment by StephenSorriaux** [comment]
Merged to master.

**Pull request merged**
