### PR TITLE
feat(tests): bump zookeper version to 3.5.4-beta

### PR DESCRIPTION
**Pull request by StephenSorriaux**
I upgraded Zookeeper version to 3.5.4-beta. Some changes occured since the 3.5.2-alpha used before :

- reconfig needs to be explicitely activated in zookeeper configuration
- reconfig needs to be used with superuser
- envi command must be added to whitelist

I added a test to check that a NoAuthError is obtained when trying to use Reconfig without superuser. I corrected Reconfig's tests to use superuser auth. I modified the testing/common.py file to add the new parameters to zookeeper server.

### CODE REVIEW

**Comment by jeffwidman** [comment]
@StephenSorriaux can you address the hound issues?

**Comment by StephenSorriaux** [comment]
@jeffwidman I just updated this PR and rebased it with master.

**Comment by jeffwidman** [comment]
@StephenSorriaux My apologies, looks like merging one of your other PR's created merge conflicts. Do you mind fixing the conflicts?

**Comment by StephenSorriaux** [comment]
@jeffwidman Sure, I will fix the conflicts

**Comment by StephenSorriaux** [comment]
@jeffwidman I just resolved conflicts

**Comment by jeffwidman** [comment]
Thanks again for this @StephenSorriaux

**Pull request merged**
