### PR TITLE
Fix handling of retry failures in Lock.acquire

### PR DESCRIPTION
**Pull request by kormat**
(Fixes https://github.com/python-zk/kazoo/issues/288)

- Make sure that self.node always exists.
- Use _best_effort_cleanup() instead of _delete_node() when we didn't
  get the lock.
- Make RetryFailedError use the existing cleanup code.
- Make _best_effort_cleanup use self.node if it's set, and fall back to
  _find_node otherwise.

### CODE REVIEW

**Comment by harlowja** [comment]
:+1:  looks ok to me

**Comment by kormat** [comment]
Can someone merge this, please?

**Comment by harlowja** [comment]
Merged ;)

**Comment by kormat** [comment]
Great, thanks :)

**Pull request merged**
